before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  goos: linux
  goarch: amd64
  image_templates:
    - "gcr.io/machine-node-linker/manage-veneer:latest"
    - "gcr.io/machine-node-linker/manage-veneer:v{{ .Major }}"
    - "gcr.io/machine-node-linker/manager-veneer:{{ .Tag }}"
